config/routes.rb
Rails.application.routes.draw do
  

  resources :users do
    resources :dashboards do
      resources :rincomes
      resources :eincomes
      resources :rcosts
      resources :ecosts
      resources :dateranges
    end
  end

  get "/log-in" => "sessions#new", as: :log_in_form
  post "/log-in" => "sessions#create", as: :log_in
  delete "/log-out" => "sessions#destroy", as: :log_out

end

app/views/partials/_dashboardlink.html.erb
<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  
  <script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
 -->
<div style="margin-left: 15px;">
	<br/>
	<br/>
	<%= link_to "Show Dashboards", user_dashboards_path(@user), method: :get %>
	<br/>
	<br/>
	<%= link_to "Show This Dashboard", user_dashboard_path(@user, @dashboard), method: :get %>
	<br/>
	<br/>
</div>

app/views/partials/_ecostindex.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
<br/>
<%= link_to "Create A Expected Cost Entry", new_user_dashboard_ecost_path(@user, @dashboard), method: :get %>
<hr>
<table>
	<thead>
		<tr>
			<th style="border: 1px solid black; padding: 5px; text-align: center; width: 275px;">Expected Cost Entry Date</th>
			<th style="border: 1px solid black; vertical-align: text-top; text-align: center; padding: 5px; width: 350px;">Expected Cost Entry Title</th>
			<th style="border: 1px solid black; padding: 5px; width: 300px; text-align: center;">Expected Cost Entry Value</th>
		</tr>
	</thead>
	<tbody>
		<% @dashboard.ecosts_not_zero.each do |eCost| %>
			<% if eCost.date >= @dashboard.df && eCost.date <= @dashboard.dt %>
				<tr style="text-align: center; background-color: grey; padding: 5px;">
					<td style="border: 1px solid black; padding: 5px;"><%= eCost.date.strftime("%a, %B %d, %Y") %></td>
					<td style="border: 1px solid black; word-wrap:break-word; padding: 5px;"><%= eCost.title %></td>
				 	<td style="border: 1px solid black; padding: 5px;">&#36;<%= eCost.ecost %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Expected Cost Entry", edit_user_dashboard_ecost_path(@user, @dashboard, eCost), method: :get %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Expected Cost Entry", user_dashboard_ecost_path(@user, @dashboard, eCost), method: :delete %></td>
				</tr>
			<% else %>
				<tr style="text-align: center;">
					<td style="border: 1px solid black; padding: 5px;"><%= eCost.date.strftime("%a, %B %d, %Y") %></td>
					<td style="border: 1px solid black; word-wrap:break-word; padding: 5px;"><%= eCost.title %></td>
				 	<td style="border: 1px solid black; padding: 5px;">&#36;<%= eCost.ecost %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Expected Cost Entry", edit_user_dashboard_ecost_path(@user, @dashboard, eCost), method: :get %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Expected Cost Entry", user_dashboard_ecost_path(@user, @dashboard, eCost), method: :delete %></td>
				</tr>
			<% end %>
		<% end %>
		<tr style="text-align: center;">
			<td></td>
			<td style="border: 1px solid black; padding: 5px;">Expected Cost Sum</td>
			<td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.ecostsum %></td>
		</tr>
	</tbody>
</table>

app/views/partials/_eincomeindex.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
<br/>
<%= link_to "Create A Expected Income Entry", new_user_dashboard_eincome_path(@user, @dashboard), method: :get %>
<hr>
<table>
	<thead>
		<tr>
			<th style="border: 1px solid black; padding: 5px; text-align: center; width: 275px;">Expected Income Entry Date</th>
			<th style="border: 1px solid black; vertical-align: text-top; text-align: center; padding: 5px; width: 350px;">Expected Income Entry Title</th>
			<th style="border: 1px solid black; padding: 5px; width: 300px; text-align: center;">Expected Income Entry Value</th>
		</tr>
	</thead>
	<tbody>
		<% @dashboard.eincomes_not_zero.each do |eIncome| %>
			<% if eIncome.date >= @dashboard.df && eIncome.date <= @dashboard.dt %>
				<tr style="text-align: center; background-color: grey; padding: 5px;">
					<td style="border: 1px solid black; padding: 5px;"><%= eIncome.date.strftime("%a, %B %d, %Y") %></td>
					<td style="border: 1px solid black; word-wrap:break-word; padding: 5px;"><%= eIncome.title %></td>
				 	<td style="border: 1px solid black; padding: 5px;">&#36;<%= eIncome.eincome %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Expected Income Entry", edit_user_dashboard_eincome_path(@user, @dashboard, eIncome), method: :get %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Expected Income Entry", user_dashboard_eincome_path(@user, @dashboard, eIncome), method: :delete %></td>
				</tr>
			<% else %>
				<tr style="text-align: center;">
					<td style="border: 1px solid black; padding: 5px;"><%= eIncome.date.strftime("%a, %B %d, %Y") %></td>
					<td style="border: 1px solid black; word-wrap:break-word; padding: 5px;"><%= eIncome.title %></td>
				 	<td style="border: 1px solid black; padding: 5px;">&#36;<%= eIncome.eincome %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Expected Income Entry", edit_user_dashboard_eincome_path(@user, @dashboard, eIncome), method: :get %></td>
				 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Expected Income Entry", user_dashboard_eincome_path(@user, @dashboard, eIncome), method: :delete %></td>
				</tr>
			<% end %>
		<% end %>
		<tr style="text-align: center;">
			<td></td>
			<td style="border: 1px solid black; padding: 5px;">Expected Income Sum</td>
			<td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.eincomesum %></td>
		</tr>
	</tbody>
</table>

app/views/partials/_rcostindex.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
<br/>
<%= link_to "Create A Real Cost Entry", new_user_dashboard_rcost_path(@user, @dashboard), method: :get %>
<hr>
<table>
	<thead>
		<tr>
		<th style="border: 1px solid black; padding: 5px; text-align: center; width: 275px;">Real Cost Entry Date</th>
		<th style="border: 1px solid black; vertical-align: text-top; text-align: center; padding: 5px; width: 350px;">Real Cost Entry Title</th>
		<th style="border: 1px solid black; padding: 5px; width: 300px; text-align: center;">Real Cost Entry Value</th>
		</tr>
	</thead>
	<tbody>
		<% @dashboard.rcosts_not_zero.each do |rCost| %>
			<% if rCost.date >= @dashboard.df && rCost.date <= @dashboard.dt %>
				<tr style="text-align: center; background-color: grey; padding: 5px;">
				<td style="border: 1px solid black; padding: 5px;"><%= rCost.date.strftime("%a, %B %d, %Y") %></td>
				<td style="border: 1px solid black; word-wrap:break-word; padding: 5px;"><%= rCost.title %></td>
			 	<td style="border: 1px solid black; padding: 5px;">&#36;<%= rCost.rcost %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Real Cost Entry", edit_user_dashboard_rcost_path(@user, @dashboard, rCost), method: :get %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Real Cost Entry", user_dashboard_rcost_path(@user, @dashboard, rCost), method: :delete %></td>
				</tr>
			<% else %>
			<tr style="text-align: center;">
				<td style="border: 1px solid black; padding: 5px;"><%= rCost.date.strftime("%a, %B %d, %Y") %></td>
				<td style="border: 1px solid black; word-wrap:break-word; padding: 5px;"><%= rCost.title %></td>
			 	<td style="border: 1px solid black; padding: 5px;">&#36;<%= rCost.rcost %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Real Cost Entry", edit_user_dashboard_rcost_path(@user, @dashboard, rCost), method: :get %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Real Cost Entry", user_dashboard_rcost_path(@user, @dashboard, rCost), method: :delete %></td>
				</tr>
			<% end %>
		<% end %>
		<tr style="text-align: center;">
			<td></td>
			<td style="border: 1px solid black; padding: 5px;">Real Cost Sum</td>
			<td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rcostsum %></td>
		</tr>
	</tbody>
</table>

app/views/partials/_rincomeindex.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
<br/>
<%= link_to "Create A Real Income Entry", new_user_dashboard_rincome_path(@user, @dashboard), method: :get %>
<hr>
<table>
	<thead>
		<tr>
		<th style="border: 1px solid black; padding: 5px; text-align: center; width: 275px;">Real Income Entry Date</th>
		<th style="border: 1px solid black; vertical-align: text-top; text-align: center; padding: 5px; width: 350px;">Real Income Entry Title</th>
		<th style="border: 1px solid black; padding: 5px; width: 300px; text-align: center;">Real Income Entry Value</th>
		</tr>
	</thead>
	<tbody>
		<% @dashboard.rincomes_not_zero.each do |rIncome| %>
			<% if rIncome.date >= @dashboard.df && rIncome.date <= @dashboard.dt %>
				<tr style="text-align: center; background-color:grey; padding: 5px">
				<td style="border: 1px solid black; padding: 5px"><%= rIncome.date.strftime("%a, %B %d, %Y") %></td>
				<td style="border: 1px solid black; word-wrap:break-word; padding: 5px"><%= rIncome.title %></td>
			 	<td style="border: 1px solid black; padding: 5px">&#36;<%= rIncome.rincome %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Real Income Entry", edit_user_dashboard_rincome_path(@user, @dashboard, rIncome), method: :get %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Real Income Entry", user_dashboard_rincome_path(@user, @dashboard, rIncome), method: :delete %></td>
				</tr>
			<% else %>
			<tr style="text-align: center;">
				<td style="border: 1px solid black; padding: 5px"><%= rIncome.date.strftime("%a, %B %d, %Y") %></td>
				<td style="border: 1px solid black; word-wrap:break-word; padding: 5px"><%= rIncome.title %></td>
			 	<td style="border: 1px solid black; padding: 5px">&#36;<%= rIncome.rincome %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 275px;"><%= link_to "Edit Real Income Entry", edit_user_dashboard_rincome_path(@user, @dashboard, rIncome), method: :get %></td>
			 	<td style="border: 1px solid black; padding: 5px; font-size: 15px; width: 300px;"><%= link_to "Delete Real Income Entry", user_dashboard_rincome_path(@user, @dashboard, rIncome), method: :delete %></td>
				</tr>
			<% end %>
		<% end %>
		<tr style="text-align: center;">
			<td></td>
			<td style="border: 1px solid black; padding: 5px">Real Income Sum</td>
			<td style="border: 1px solid black; padding: 5px">&#36;<%= @dashboard.rincomesum %></td>
		</tr>
	</tbody>
</table>