config/routes.rb
Rails.application.routes.draw do
  

  resources :users do
    resources :dashboards do
      resources :rincomes
      resources :eincomes
      resources :rcosts
      resources :ecosts
      resources :dateranges
    end
  end

  get "/log-in" => "sessions#new", as: :log_in_form
  post "/log-in" => "sessions#create", as: :log_in
  delete "/log-out" => "sessions#destroy", as: :log_out

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :dashboards
	has_many :rincomes
	has_many :eincomes
	has_many :rcosts
	has_many :ecosts
	
	validates_presence_of :email
	validates_presence_of :password
	validates_uniqueness_of :email	

	attr_accessor :password
	before_save :encrypt_password
	validates_confirmation_of :password
	
	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end
	
	def self.authenticate(email, password)
		user = User.where(email: email).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to(user_dashboards_path(@user))
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      render "new"
    end
  end
  def show
  end
  def update
  end
  def destroy
  end
  def edit
  end
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<br/>
<br/>
<%= link_to "Go To Login Page", log_in_form_path, method: :get %>
<br/>
<br/>
<h1>Sign Up</h1>
<%=form_for @user do |f| %>
<%=f.label :email %>
<%=f.text_field :email %>
<%=f.label :password %>
<%=f.password_field :password %>
<%=f.label :password_confirmation %>
<%=f.password_field :password_confirmation %>
<%=f.submit "Sign Up" %>
<%end%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>