config/routes.rb
Rails.application.routes.draw do
  

  resources :users do
    resources :dashboards do
      resources :rincomes
      resources :eincomes
      resources :rcosts
      resources :ecosts
      resources :dateranges
    end
  end

  get "/log-in" => "sessions#new", as: :log_in_form
  post "/log-in" => "sessions#create", as: :log_in
  delete "/log-out" => "sessions#destroy", as: :log_out

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	belongs_to :user
	has_many :rincomes
	has_many :eincomes
	has_many :rcosts
	has_many :ecosts
	has_many :dateranges
	validates_presence_of :title
	validates_presence_of :balance

	def getdate
		if Daterange.last == nil
			d = Daterange.new
			d.datefrom = DateTime.now
			d.dateto = DateTime.now
			return d
		else
			return Daterange.last
		end
	end

	def df
		getdate.datefrom
	end
	def dt
		getdate.dateto
	end


	def currentbalance
		return self.balance
	end

	def rincomes_not_zero 
		rincomes.select { |r| r.rincome > 0 && !r.date.nil?}.sort_by! {|ri| ri.date}
	end

	def rincomesum
		risum = 0
		rincomes_not_zero.each do |r|
			risum += r.rincome
		end
		return risum
	end

	def eincomes_not_zero 
		eincomes.select { |e| e.eincome > 0 && !e.date.nil?}.sort_by! {|ei| ei.date}
	end

	def eincomesum
		eisum = 0
		eincomes_not_zero.each do |e|
			eisum += e.eincome
		end
		return eisum
	end

	def tei
		tei = eincomesum + rincomesum
	end

	def rcosts_not_zero 
		rcosts.select { |r| r.rcost > 0 && !r.date.nil?}.sort_by! {|rc| rc.date}
	end

	def rcostsum
		rcsum = 0
		rcosts_not_zero.each do |r|
			rcsum += r.rcost
		end
		return rcsum
	end

	def ecosts_not_zero 
		ecosts.select { |e| e.ecost > 0 && !e.date.nil?}.sort_by! {|ec| ec.date}
	end

	def ecostsum
		ecsum = 0
		ecosts_not_zero.each do |e|
			ecsum += e.ecost
		end
		return ecsum
	end

	def tec
		tec = ecostsum + rcostsum
	end

	def realvalue
		realvalue = 0
		realvalue = (currentbalance + rincomesum - rcostsum)
		return realvalue
	end

	def exprealvalue
		exprealvalue = 0
		exprealvalue = (currentbalance + tei - tec)
		return exprealvalue
	end



	def rangeri
		rincomes_not_zero.select { |r| df <= r.date && dt >= r.date}
	end
	def rangerc
		rcosts_not_zero.select { |r| df <= r.date && dt >= r.date}
	end
	def rangeei
		eincomes_not_zero.select { |r| df <= r.date && dt >= r.date}
	end
	def rangeec
		ecosts_not_zero.select { |r| df <= r.date && dt >= r.date}
	end

	def rangerisum
		rrisum = 0
		rangeri.each do |r|
			rrisum += r.rincome
		end
		return rrisum
	end
	def rangeeisum
		reisum = 0
		rangeei.each do |r|
			reisum += r.eincome
		end
		return reisum
	end
	def rtei
		rtei = rangeeisum + rangerisum
	end

	def rangercsum
		rrcsum = 0
		rangerc.each do |r|
			rrcsum += r.rcost
		end
		return rrcsum
	end
	def rangeecsum
		recsum = 0
		rangeec.each do |r|
			recsum += r.ecost
		end
		return recsum
	end
	def rtec
		rtec = rangeecsum + rangercsum
	end

	def brangeri
		rincomes_not_zero.select { |r| df > r.date}
	end
	def brangerc
		rcosts_not_zero.select { |r| df > r.date}
	end
	def brangeei
		eincomes_not_zero.select { |r| df > r.date}
	end
	def brangeec
		ecosts_not_zero.select { |r| df > r.date}
	end

	def brangerisum
		brrisum = 0
		brangeri.each do |r|
			brrisum += r.rincome
		end
		return brrisum
	end
	def brangeeisum
		breisum = 0
		brangeei.each do |r|
			breisum += r.eincome
		end
		return breisum
	end
	def brtei
		brtei = brangeeisum + brangerisum
	end

	def brangercsum
		brrcsum = 0
		brangerc.each do |r|
			brrcsum += r.rcost
		end
		return brrcsum
	end
	def brangeecsum
		brecsum = 0
		brangeec.each do |r|
			brecsum += r.ecost
		end
		return brecsum
	end
	def brtec
		brtec = brangeecsum + brangercsum
	end

	def rangersb
		rangersb = 0
		rangersb = (currentbalance + brangerisum - brangercsum)
		return rangersb
	end
	def rangeesb
		rangeesb = 0
		rangeesb = (currentbalance + brtei - brtec)
		return rangeesb
	end


	def rangerealvalue
		rangerealvalue = 0
		rangerealvalue = (rangersb + rangerisum - rangercsum)
		return rangerealvalue
	end

	def rangeexprealvalue
		rangeexprealvalue = 0
		rangeexprealvalue = (rangeesb + rtei - rtec)
		return rangeexprealvalue
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @dashboard = Dashboard.where("user_id = ?", @user.id)
  end
  def show
    @user = User.find(params[:user_id])
    @dashboard = Dashboard.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @dashboard = Dashboard.new
    @dashboard.user_id = @user.id
  end

  def edit
    @user = User.find(params[:user_id])
    @dashboard = Dashboard.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @dashboard = Dashboard.find(params[:id])
    @dashboard.title = params[:dashboard][:title]
    balancetemp = params[:dashboard][:balance]
    @dashboard.balance = balancetemp.gsub(/,/, '').to_f
    if @dashboard.save
      flash[:notice] = "Your Dashboard was edited successfully."
      redirect_to(user_dashboard_path(@user, @dashboard))
    else
      flash[:alert] = "There was a problem editing your Dashboard."
      render "edit"
    end
  end

  def create
    @user = User.find(params[:user_id])
    @dashboard = Dashboard.new
    @dashboard.title = params[:dashboard][:title]
    balancetemp = params[:dashboard][:balance]
    @dashboard.balance = balancetemp.gsub(/,/, '').to_f
    @dashboard.user_id = @user.id
    if @dashboard.save
      flash[:notice] = "Your Dashboard was created successfully."
      redirect_to(user_dashboards_path(@user))
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    dashboard = Dashboard.find(params[:id])
    if dashboard.delete
      flash[:notice] = "Your Dashboard was deleted successfully."
      redirect_to(user_dashboards_path(@user))
    else
      flash[:alert] = "There was a problem deleting your Dashboard."
      redirect_to(user_dashboards_path(@user))
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/create.html.erb
<h1>Dashboards#create</h1>
<p>Find me in app/views/dashboards/create.html.erb</p>

app/views/dashboards/destroy.html.erb
<h1>Dashboards#destroy</h1>
<p>Find me in app/views/dashboards/destroy.html.erb</p>

app/views/dashboards/edit.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
<br/>
<% @dashboard.errors.full_messages.each do |error| %>
<%= error %>
<% end %>

<%= render "partials/dashboardlink" %>

	<table class="table table-striped" style="margin-left: 15px;">
		<thead>
			<tr>
			<th style="border: 1px solid black; text-align: center; width: 250px;">Dashboard Title</th>
			<th style="border: 1px solid black; text-align: center; width: 300px;">Dashboard Starting Balance</th>
			<th style="border: none;"></th>
			</tr>
		</thead>
		<tbody>
			<tr style="text-align: center;">
			<td style="border: 1px solid black;"><%= @dashboard.title %></td>
			<td style="border: 1px solid black;">&#36;<%= @dashboard.balance %></td>
			</tr>
		</tbody>
	</table>

<div style="margin-left: 15px;">
	<%= form_for [@user, @dashboard] do |f| %>

	<%=f.label :title %>
	<%=f.text_field :title %>
	<%=f.label :Account_Balance %>
	<%=f.text_field :balance %>

	<%=f.submit :"Submit Edit" %>
	<% end %>
</div>

app/views/dashboards/index.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  <script>
  $(function() {
    $( "#accordion" )
      .accordion({
        header: "> div > h3"
      })
      .sortable({
        axis: "y",
        handle: "h3",
        stop: function( event, ui ) {
          // IE doesn't register the blur when sorting
          // so trigger focusout handlers to remove .ui-state-focus
          ui.item.children( "h3" ).triggerHandler( "focusout" );
 
          // Refresh accordion to handle new order
          $( this ).accordion( "refresh" );
        }
      });
  });
  </script>
  <script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
  
<br/>
<br/>
<%= link_to "Create A New Dashboard", new_user_dashboard_path(@user), method: :get %>
<br/>
<br/>
<div id="accordion">
  <% @dashboard.each do |dash| %>
  <div class="group">
    <h3><u>Dashboard Title</u>: <%= dash.title %> -- -- <%= link_to "Show This Dashboard", user_dashboard_path(@user, dash), method: :get %> / <%= link_to "Edit Dashboard", edit_user_dashboard_path(@user, dash), method: :get %> / <%= link_to "Delete Dashboard", user_dashboard_path(@user, dash), method: :delete %></h3>
    <div>
    	<u>Dashboard Starting Balance</u>: &#36;<%= dash.balance %>
    </div>
  </div>
  <% end %>
</div>
<br/>
<br/>
<%= link_to "Log_Out", log_out_path, method: :delete %>

app/views/dashboards/new.html.erb
<br/>
<% @dashboard.errors.full_messages.each do |error| %>
<%= error %>
<br/>
<% end %>

<br/>
<br/>
<div style="margin-left: 15px;">
	 <%= link_to "Show Dashboards", user_dashboards_path(@user.id), method: :get %>
	<br/>
	<br/>

	<%= form_for [@user, @dashboard] do |f| %>

	<%=f.label :Title %>
	<%=f.text_field :title %>	
	<%=f.label :Account_Balance %>
	<%=f.text_field :balance %>

	<%=f.submit :create %>

	<% end %>
</div>

app/views/dashboards/show.html.erb
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>
  <script>
  $(function() {
    $( "input[type=submit], a, button" )
      .button()
      .click(function( event ) {
        event.preventDefault();
      });
  });
  </script>
<br/>
<br/>
<div style="margin-left: 15px;">
<%= link_to "Show Dashboards", user_dashboards_path(@user), method: :get %>
<br/>
  <h3><u>Dashboard Title</u>: <i><%= @dashboard.title %></i></h3>
	<h3><u>Dashboard Starting Balance</u>: <i>&#36;<%= @dashboard.balance %></i> -- <small><%= link_to "Edit Dashboard", edit_user_dashboard_path(@user, @dashboard), method: :get %></small></h3>
</div>
<div id="tabs" style="margin-left: 5px; margin-right: 5px;">
  <ul>
    <li><a href="#tabs-1">Real Incomes</a></li>
    <li><a href="#tabs-2">Real Costs</a></li>
    <li><a href="#tabs-3">Expected Incomes</a></li>
    <li><a href="#tabs-4">Expected Costs</a></li>
  </ul>
  <div id="tabs-1">
  	<%= render "partials/rincomeindex" %>
  </div>
  <div id="tabs-2">
  	<%= render "partials/rcostindex" %>
  </div>
  <div id="tabs-3">
  	<%= render "partials/eincomeindex" %>
  </div>
  <div id="tabs-4">
  	<%= render "partials/ecostindex" %>
  </div>
</div>
<br/>
<div style="float: left; padding: 10px;">
  <table class="table table-striped" style="width: auto;">
    <thead>
      <tr>
        <th style="border: 1px solid black;">Dashboard Starting Balance</th>
        <th style="border: 1px solid black;">Total Real Income</th>
        <th style="border: 1px solid black;">Total Real Cost</th>
        <th style="border: 1px solid black;">Real Value</th>
      <tr>
    </thead>
    <tbody>
      <tr style="text-align: center;" style="width: auto;">
        <td style="border: 1px solid black;">&#36;<%= @dashboard.balance %></td>
        <td style="border: 1px solid black;">&#36;<%= @dashboard.rincomesum %></td>
        <td style="border: 1px solid black;">&#36;<%= @dashboard.rcostsum %></td>
        <% if @dashboard.realvalue > 0 %>
          <td style="border: 1px solid black; background-color: lime">&#36;<%= @dashboard.realvalue %></td>
          <% elsif @dashboard.realvalue == 0 %>
          <td style="border: 1px solid black;">&#36;<%= @dashboard.realvalue %></td>
          <% else %>
          <td style="border: 1px solid black; background-color: red">&#36;<%= @dashboard.realvalue %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <table class="table table-striped" style="width: auto;">
    <thead>
      <tr>
        <th style="border: 1px solid black;">Total Expected Income</th>
        <th style="border: 1px solid black;">Total Expected Cost</th>
        <th style="border: 1px solid black;">Expected Real Value</th>
      <tr>
    </thead>
    <tbody>
      <tr style="text-align: center;">
        <td style="border: 1px solid black;">&#36;<%= @dashboard.tei %></td>
        <td style="border: 1px solid black;">&#36;<%= @dashboard.tec %></td>
        <% if @dashboard.exprealvalue > 0 %>
          <td style="border: 1px solid black; background-color: lime">&#36;<%= @dashboard.exprealvalue %></td>
          <% elsif @dashboard.exprealvalue == 0 %>
          <td style="border: 1px solid black;">&#36;<%= @dashboard.exprealvalue %></td>
          <% else %>
          <td style="border: 1px solid black; background-color: red">&#36;<%= @dashboard.exprealvalue %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
<div style="float: right; border-left: 2px solid black; padding: 10px;">
  <%= link_to "Create A Date Range (YYYY/MM/DD)", new_user_dashboard_daterange_path(@user, @dashboard), method: :get %>
  <br/>
  <h3>
    <u>Current Range</u> - <small>highlighted above in grey</small>
    <br/>
    <br/>
    From: <i><%= @dashboard.df.strftime("%A, %B %d, %Y") %></i>
    <br/>
    To: <i><%= @dashboard.dt.strftime("%A, %B %d, %Y") %></i>
  </h3>
  <br/>
  <table class="table table-striped" style="width: auto;">
    <thead>
      <tr>
        <th style="border: 1px solid black; padding: 5px;">Range Starting Balance</th>
        <th style="border: 1px solid black; padding: 5px;">Range Total Real Income</th>
        <th style="border: 1px solid black; padding: 5px;">Range Total Real Cost</th>
        <th style="border: 1px solid black; padding: 5px;">Range Real Value</th>
      <tr>
    </thead>
    <tbody>
      <tr style="text-align: center;" style="width: auto;">
        <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rangersb %></td>
        <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rangerisum %></td>
        <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rangercsum %></td>
        <% if @dashboard.rangerealvalue > 0 %>
          <td style="border: 1px solid black; background-color: lime; padding: 5px;">&#36;<%= @dashboard.rangerealvalue %></td>
          <% elsif @dashboard.rangerealvalue == 0 %>
          <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rangerealvalue %></td>
          <% else %>
          <td style="border: 1px solid black; background-color: red; padding: 5px;">&#36;<%= @dashboard.rangerealvalue %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <table class="table table-striped" style="width: auto; float: right;">
    <thead>
      <tr>
        <th style="border: 1px solid black; padding: 5px;">Range Starting Expected Balance</th>
        <th style="border: 1px solid black; padding: 5px;">Range Total Expected Income</th>
        <th style="border: 1px solid black; padding: 5px;">Range Total Expected Cost</th>
        <th style="border: 1px solid black; padding: 5px;">Range Expected Real Value</th>
      <tr>
    </thead>
    <tbody>
      <tr style="text-align: center;">
        <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rangeesb %></td>
        <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rtei %></td>
        <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rtec %></td>
        <% if @dashboard.rangeexprealvalue > 0 %>
          <td style="border: 1px solid black; background-color: lime; padding: 5px;">&#36;<%= @dashboard.rangeexprealvalue %></td>
          <% elsif @dashboard.rangeexprealvalue == 0 %>
          <td style="border: 1px solid black; padding: 5px;">&#36;<%= @dashboard.rangeexprealvalue %></td>
          <% else %>
          <td style="border: 1px solid black; background-color: red; padding: 5px;">&#36;<%= @dashboard.rangeexprealvalue %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
<br/>
<br/>
<br/>
<div style="clear: both;">
<%= link_to "Log_Out", log_out_path, method: :delete %>
</div>

app/views/dashboards/update.html.erb
<h1>Dashboards#update</h1>
<p>Find me in app/views/dashboards/update.html.erb</p>